Revert "logs"
This reverts commit e1eeae5b6037f0129c3b21b8b29b41b2f94ded45.

diff --git a/tests/test_library b/tests/test_library
--- a/tests/test_library
+++ b/tests/test_library
@@ -5,49 +5,30 @@ cd $(dirname "$0")/../
 script_path=$(pwd)
 cd "${result_path}"
 
-result_logs() {
-  # $1 = test name
-  # $2 = status: "ok" / "failed" / "configuration failed" / "expected error"
-  #              "skipped" / "ncat (nc) failed" / "shouldn't work"
-  # $3 = file name: "stunnel" / "error"
-
-  if [ "$2" = "expected error" ]
-    then # expected error - it's ok
-      printf "%-35s\t%s\n" "test $1" "ok"
-     else
-      printf "%-35s\t%s\n" "test $1" "$2"
-     fi
-
-  if [ "$2" != "ok" ] && [ "$2" != "ncat (nc) failed" ]
-    then
-      printf "%-35s\t%s\n" "test $1" "$2" >> "results.log"
-    fi
-
-  if [ "$2" = "failed" ] || [ "$2" = "configuration failed" ] || [ "$2" = "shouldn't work" ]
+screen_result() {
+  printf "%-35s\t%s\n" "test $1" "$2"
+  if [ "$2" = "failed" ]
     then # file with stunnel error logs
       printf "%-35s\t%s\n" "error logs" "logs/$1.log"
-      cat "$3.log" > "$1.log"
-    else
-      cat "temp.log" >> "results.log" 2>> "stderr_nc.log"
     fi
-
   return 0
 }
 
-exit_logs() {
-  case "$2" in
-    "ok") result_logs "$1" "ok" "UNUSED PATTERN";;
-    "failed") result_logs "$1" "failed" "stunnel";;
-    "configuration failed") result_logs "$1" "configuration failed" "error";;
-    "expected error") result_logs "$1" "expected error" "UNUSED PATTERN";;
-    "skipped") result_logs "$1" "skipped" "error";;
-    "ncat (nc) failed") result_logs "$1" "failed" "stunnel";;
-    "shouldn't work") result_logs "$1" "shouldn't work" "stunnel";;
-  esac
+file_result() {
+  if [ -s "$2.log" ] && [ "$3" != "expected error" ]
+    then # $2 = "stunnel" / "error"
+      cat "$2.log" > "$1.log"
+    fi
+  if [ "$3" = "skipped" ]
+    then
+      printf "%-35s\t%s\n" "test $1" "$3" >> "results.log"
+    else
+      printf "%-35s\t%s\n" "test $1" "$3" > "temp.log"
+    fi
   return 0
 }
 
-clean_logs() {
+clean_logs(){
   rm -f "stunnel.log"
   rm -f "temp.log"
   rm -f "error.log"
@@ -56,9 +37,9 @@ clean_logs() {
   return 0
 }
 
-waiting_for() {
+waiting_for(){
   mkfifo "fifo"
-  (cat "$1.log"; tail -f "$1.log") > "fifo" 2>> "stderr_nc.log" &
+  (cat "$1.log"; tail -f "$1.log") > "fifo" &
   pid_tail=$!
   (sleep 3; echo "TIMEOUT") > "fifo" &
   pid_timeout=$!
@@ -71,7 +52,7 @@ waiting_for() {
   rm -f "fifo"
 }
 
-connecting_ncat() {
+connecting_ncat(){
   result=0
   mkfifo "nodata"
   printf "\n%s\n" "test $1" > "stderr_nc.log"
@@ -103,15 +84,15 @@ connecting_ncat() {
 }
 
 killing_stunnel() {
-  waiting_for "stunnel" "Service .* finished" "Sent socket write shutdown" "UNUSED PATTERN"
+  waiting_for "stunnel" "Service .* finished" "Child process .* finished" "child started" "UNUSED PATTERN"
   kill -TERM $(tail "stunnel.pid") 2>> "stderr.log"
   return 0
 }
 
 reload_stunnel() {
-  waiting_for "stunnel" "stunnel.pid" "UNUSED PATTERN" "UNUSED PATTERN"
+  waiting_for "stunnel" "stunnel.pid" "UNUSED PATTERN" "UNUSED PATTERN" "UNUSED PATTERN"
   kill -HUP $(tail "stunnel.pid") 2>> "stderr.log"
-  waiting_for "stunnel" "127.0.0.1:${http1}" "UNUSED PATTERN" "UNUSED PATTERN"
+  waiting_for "stunnel" "127.0.0.1:${http1}" "UNUSED PATTERN" "UNUSED PATTERN" "UNUSED PATTERN"
   return 0
 }
 
@@ -121,23 +102,25 @@ expected_success() {
     then
       if connecting_ncat "$1" "success" "$2"
         then
+          killing_stunnel
           if grep -q "test $1.*success" "temp.log"
             then
-              exit_code="ok"
+              screen_result "$1" "ok"
             else # test failed
-              exit_code="failed"
+              file_result "$1" "stunnel" "failed"
+              screen_result "$1" "failed"
               result=1
             fi
         else # ncat (nc) failed
-          exit_code="ncat (nc) failed"
+          killing_stunnel
+          screen_result "$1" "ncat (nc) failed"
           result=1
         fi
-        killing_stunnel
     else # configuration failed
-      exit_code="configuration failed"
+      file_result "$1" "error" "configuration failed"
+      screen_result "$1" "configuration failed"
       result=1
     fi
-  exit_logs "$1" "$exit_code"
   return $result
 }
 
@@ -147,22 +130,24 @@ expected_failure() {
     then
       if connecting_ncat "$1" "shouldn't work" "$2"
         then
+          killing_stunnel
           if grep -q "test $1.*shouldn't work" "temp.log"
             then # ops...stunnel works
-              exit_code="shouldn't work"
+              screen_result "$1" "shouldn't work"
               result=1
             else
-              exit_code="expected error"
+              file_result "$1" "stunnel" "expected error"
+              screen_result "$1" "ok"
             fi
         else # ncat (nc) failed
-          exit_code="ncat (nc) failed"
+          killing_stunnel
+          screen_result "$1" "ncat (nc) failed"
           result=1
         fi
-        killing_stunnel
     else # configuration failed, but it is ok
-      exit_code="expected error"
+      file_result "$1" "error" "expected error"
+      screen_result "$1" "ok"
     fi
-  exit_logs "$1" "$exit_code"
   return $result
 }
 
@@ -172,29 +157,54 @@ execute_program() {
   if [ ! -s "error.log" ]
     then
       cat "nodata" | "$2" 127.0.0.1 "$http1" -vv > "temp.log" 2>>"stderr.log" &
-      pid_nce=$!
+      pid_nc=$!
       killing_stunnel
-      kill -TERM ${pid_nce} 2>> "stderr.log"
+      kill -TERM ${pid_nc} 2>> "stderr.log"
       echo "somedata" >"nodata" 2>> "stderr.log"
       rm -f "nodata"
       if grep -q "test $1.*success" "temp.log"
         then
           if grep -q "$1_error" "temp.log"
             then # only for redirect tests
-              exit_code="failed"
+              file_result "$1" "stunnel" "failed"
+              screen_result "$1" "failed"
               result=1
             else
-              exit_code="ok"
+              screen_result "$1" "ok"
           fi
         else # test failed
-          exit_code="failed"
+          file_result "$1" "stunnel" "failed"
+          screen_result "$1" "failed"
           result=1
         fi
     else # configuration failed
-      exit_code="configuration failed"
+      file_result "$1" "error" "configuration failed"
+      screen_result "$1" "configuration failed"
       result=1
     fi
-  exit_logs "$1" "$exit_code"
+  return $result
+}
+
+check_prio(){
+  result=0
+  if [ $1 = "037_failover_prio1" ]
+    then
+      serv="server_2\] accepted connection"
+    else
+      serv="server_1\] accepted connection"
+    fi
+  if ! grep -q "$serv" "stunnel.log"
+    then # second server doesn't accept any client
+      if [ $2 -eq $3 ]
+        then # last successed turn of the loop
+          printf "%-35s\t%s\n" "test $1" "success" > "temp.log"
+          screen_result "$1" "ok"
+        fi
+    else # error - second server accepts a client
+        file_result "$1" "stunnel" "failed"
+        screen_result "$1" "failed"
+        result=1
+    fi
   return $result
 }
 
@@ -205,60 +215,31 @@ loop_prio() {
   start $i 2> "error.log"
   if [ ! -s "error.log" ]
     then
-      waiting_for "stunnel" "Created pid file" "UNUSED PATTERN" "UNUSED PATTERN"
-      mv "stunnel.log" "stunnel_0.log"
-      kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
       while [ $i -le $max ] && [ $result -eq 0 ]
         do
           if connecting_ncat "$1" "success" "$2"
             then
-              waiting_for "stunnel" "Service .* finished" "UNUSED PATTERN" "UNUSED PATTERN"
               if grep -q "test $1.*success" "temp.log"
                 then
-                  if [ $1 = "037_failover_prio1" ]
-                    then
-                      serv="server_2\] accepted connection"
-                    else
-                      serv="server_1\] accepted connection"
-                    fi
-		  if ! grep -q "$serv" "stunnel.log"
-		    then # second server doesn't accept any client
-		      if [ $i -eq $max ]
-			then # last successed turn of the loop
-			  exit_code="ok"
-			fi
-		    else # error - second server accepts a client
-                      exit_code="failed"
-		      result=1
-		    fi
+                  check_prio "$1" "$i" "$max"
+                  result=$?
                 else # stunnel doesn't work
-                  exit_code="failed"
+                  file_result "$1" "stunnel" "failed"
+                  screen_result "$1" "failed"
                   result=1
                 fi
             else # ncat (nc) failed
-              exit_code="ncat (nc) failed"
+              screen_result "$1" "ncat (nc) failed"
               result=1
             fi
-          waiting_for "stunnel" "Service .* finished" "UNUSED PATTERN" "UNUSED PATTERN"
-          mv "stunnel.log" "stunnel_$i.log"
-          kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
           i=$((i + 1))
-        done
-      cat "stunnel_0.log" > "stunnel.log"
-      rm -f "stunnel_0.log"
-      j=1
-      while [ $j -lt $i ]
-        do
-          cat "stunnel_$j.log" >> "stunnel.log"
-          rm -f "stunnel_$j.log"
-          j=$((j + 1))
         done
       killing_stunnel
     else # configuration failed
-      exit_code="configuration failed"
+      file_result "$1" "error" "configuration failed"
+      screen_result "$1" "configuration failed"
       result=1
     fi
-  exit_logs "$1" "$exit_code"
   return $result
 }
 
@@ -272,58 +253,50 @@ loop_rr() {
   start $i 2> "error.log"
   if [ ! -s "error.log" ]
     then
-      waiting_for "stunnel" "Created pid file" "UNUSED PATTERN" "UNUSED PATTERN"
-      mv "stunnel.log" "stunnel_0.log"
-      kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
       while [ $i -le $max ] && [ $result -eq 0 ]
         do
           if connecting_ncat "$1" "success" "$2"
             then
-              waiting_for "stunnel" "Service .* finished" "UNUSED PATTERN" "UNUSED PATTERN"
               if ! grep -q "test $1.*success" "temp.log"
                 then # stunnel doesn't work
-                  exit_code="failed"
+                  file_result "$1" "stunnel" "failed"
+                  screen_result "$1" "failed"
                   result=1
                 fi
             else # ncat (nc) failed
-              exit_code="ncat (nc) failed"
+              screen_result "$1" "ncat (nc) failed"
               result=1
             fi
-          mv "stunnel.log" "stunnel_$i.log"
-          kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
+
           i=$((i + 1))
         done
-      cat "stunnel_0.log" > "stunnel.log"
-      rm -f "stunnel_0.log"
-      j=1
-      while [ $j -lt $i ]
-        do
-          cat "stunnel_$j.log" >> "stunnel.log"
-          rm -f "stunnel_$j.log"
-          j=$((j + 1))
-        done
-      killing_stunnel
       first=$(grep -c "server_1\] accepted connection" "stunnel.log")
       second=$(grep -c "server_2\] accepted connection" "stunnel.log")
       third=$(grep -c "server_3\] accepted connection" "stunnel.log")
+      killing_stunnel
     else # configuration failed
-      exit_code="configuration failed"
+      file_result "$1" "error" "configuration failed"
+      screen_result "$1" "configuration failed"
       result=1
     fi
+    if [ $result -eq 0 ] && [ -e "stunnel.log" ]
+      then
+        file_result "$1" "stunnel" "success"
+      fi
     if [ $result -eq 0 ]
       then
         product=$((first * second * third))
         if [ $product -ne 0 ]
           then # round robin
             printf "%-35s\t%s\n" "test $1: $first x $second x $third" "success" > "temp.log"
-            exit_code="ok"
+            screen_result "$1" "ok"
+            rm "$1.log"
           else
             printf "%-35s\t%s\n" "test $1: $first x $second x $third" "failed" > "temp.log"
-            exit_code="failed"
+            screen_result "$1" "failed"
             result=1
           fi
       fi
-  exit_logs "$1" "$exit_code"
   return $result
 }
 
@@ -336,6 +309,7 @@ test_log_for() {
     "rr") loop_rr "$1" "$3";;
   esac
   result=$?
+  cat "temp.log" >> "results.log"
   clean_logs
   return $result
 }
