autodetection

diff --git a/tests/test_library b/tests/test_library
--- a/tests/test_library
+++ b/tests/test_library
@@ -120,55 +120,27 @@ waiting_for() {
 }
 
 find_free() {
-  # finding a free port using netstat/ss/lsof tools
-  # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
+  # finding a free port
+  # $1 = mynetstat name: "netstat -a -n" / "ss -a -n -l" / "lsof -i -n -P"
 
-  result=0
-  if [ -n "$(command -v netstat)" ] && PATH="${PATH}:/sbin:/usr/sbin" netstat -an > "/dev/null" 2>&1
-    then
-      while PATH="${PATH}:/sbin:/usr/sbin" netstat -an | grep "$http_find" | grep "LISTEN" >> "stderr_nc.log"
-        do
-          http_find=$((http_find+1))
-        done
-    elif [ -n "$(command -v ss)" ] && PATH="${PATH}:/sbin:/usr/sbin" ss -anl > "/dev/null" 2>&1
-      then
-        while PATH="${PATH}:/sbin:/usr/sbin" ss -anl | grep "$http_find" >> "stderr_nc.log"
-          do
-            http_find=$((http_find+1))
-          done
-    elif [ -n "$(command -v lsof)" ]
-      then
-        while PATH="${PATH}:/sbin:/usr/sbin" lsof -i -n -P | grep "$http_find" | grep "LISTEN" >> "stderr_nc.log"
-          do
-            http_find=$((http_find+1))
-          done
-    else # error not handled
-      printf "\n%s\n" "netstat / ss / lsof not found in \$PATH" >> "stderr_nc.log"
-      result=1
-   fi
-  return $result
+  while $mynetstat $opt_net | grep "$http_find" | grep "LISTEN" >> "stderr_nc.log"
+    do
+      http_find=$((http_find+1))
+    done
+  return 0
 }
 
 check_ports() {
   # seting the initial ports
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   result=0
   printf "\n%s\n" "test $1" >> "stderr_nc.log"
   http_find=8080
-  if ! find_free $1 $2
-     then
-       result=1
-     fi
+  find_free
   http_nc=$http_find
-
   http_find=4567
-  if ! find_free $1 $2
-     then
-       result=1
-     fi
+  find_free
   https_free=$http_find
 
   http1=$((http_nc+1))
@@ -177,7 +149,7 @@ check_ports() {
   https1=4433
   https2=4434
   https3=4435
-  return $result
+  return 0
 }
 
 bind_http_ports(){
@@ -268,21 +240,23 @@ reload_stunnel() {
   # $1 = test name
 
   local result=0
+  printf "\n%s\n" "test $1 - reload stunnel" >> "stderr_nc.log"
   if [ ! -s "error.log" ]
     then
       change_config
       waiting_for "stunnel" "stunnel.pid"
       kill -HUP $(tail "stunnel.pid") 2>> "stderr_nc.log"
-      waiting_for "stunnel" "127.0.0.1:${http1}"
-      grep "Error binding service" "error.log" >> "stderr_nc.log"
+      waiting_for "stunnel" "127.0.0.1:$http1"
+      grep "Error binding service .*$http1" "error.log" >> "stderr_nc.log"
       while grep -q "Error binding service .*$http1" "stunnel.log"
         do
           http1=$((http1+1))
           change_config
           kill -HUP $(tail "stunnel.pid") 2>> "stderr_nc.log"
-          waiting_for "stunnel" "127.0.0.1:${http1}"
-          grep "Error binding service" "error.log" >> "stderr_nc.log"
+          waiting_for "stunnel" "127.0.0.1:$http1"
+          grep "Error binding service .*$http1" "error.log" >> "stderr_nc.log"
         done
+      printf "\n%s\n" "test $1 - accept port: $http1" >> "stderr_nc.log"
     else
       printf "\n%s" "$1 error: failed to reload the configuration file" >> "error.log"
       result=1
@@ -291,67 +265,40 @@ reload_stunnel() {
 }
 
 check_listening() {
-  # waiting for netcat listening on port using netstat/ss/lsof tools
+  # waiting for netcat listening on port
   # $1 = port number
 
   result=0
-  if [ -n "$(command -v netstat)" ] && PATH="${PATH}:/sbin:/usr/sbin" netstat -an > "/dev/null" 2>&1
-    then
-      while [ $result -eq 0 ] && ! PATH="${PATH}:/sbin:/usr/sbin" netstat -an | grep "$1" | grep "LISTEN" # >> "stderr_nc.log"
-        do
-          printf "\n%s\n" "waiting for netcat listening on $1" # >> "stderr_nc.log"
-          if grep -q -e "failed" -e "usage" -e "QUITTING" -e "invalid" -e "command not found" "stderr_nc.log"
-            then
-              result=1
-            fi
-        done
-    elif [ -n "$(command -v ss)" ] && PATH="${PATH}:/sbin:/usr/sbin" ss -anl > "/dev/null" 2>&1
-      then
-        while [ $result -eq 0 ] && ! PATH="${PATH}:/sbin:/usr/sbin" ss -anl | grep "$1" >> "stderr_nc.log"
-          do
-            printf "\n%s\n" "waiting for netcat listening on $1" >> "stderr_nc.log"
-            if grep -q -e "failed" -e "usage" -e "QUITTING" -e "invalid" -e "command not found" "stderr_nc.log"
-              then
-                result=1
-              fi
-          done
-    elif [ -n "$(command -v lsof)" ] && PATH="${PATH}:/sbin:/usr/sbin" lsof -i -n -P > "/dev/null" 2>&1
-      then
-        while [ $result -eq 0 ] && ! PATH="${PATH}:/sbin:/usr/sbin" lsof -i -n -P | grep "$1" | grep "LISTEN" >> "stderr_nc.log"
-          do
-            printf "\n%s\n" "waiting for netcat listening on $1" >> "stderr_nc.log"
-            if grep -q -e "failed" -e "usage" -e "QUITTING" -e "invalid" -e "command not found" "stderr_nc.log"
-              then
-                result=1
-              fi
-          done
-    else # error not handled
-      printf "\n%s\n" "netstat / ss / lsof not found in \$PATH" >> "stderr_nc.log"
-      result=1
-    fi
+  while [ $result -eq 0 ] && ! $mynetstat $opt_net | grep "$1" | grep "LISTEN" >> "stderr_nc.log"
+    do
+      printf "\n%s\n" "waiting for netcat listening on $1" >> "stderr_nc.log"
+      if grep -q -e "failed" -e "usage" -e "QUITTING" -e "invalid" -e "command not found" "stderr_nc.log"
+        then
+          result=1
+        fi
+    done
   return $result
 }
 
 connecting_ncat() {
   # $1 = test name
   # $2 = string to send
-  # $3 = netcat name: "ncat" / "nc"
 
   local result=0
   mkfifo "nodata" 2>> "stderr_nc.log"
   printf "\n%s\n" "test $1 - netcat connection" >> "stderr_nc.log"
-  if [ "$3" = "nc" ]
+  if [ "$mynetcat" = "nc" ]
     then # nc
-      if man "$3" | grep -q  "error to use this option in conjunction"
+      if man "$mynetcat" | grep -q  "error to use this option in conjunction"
         then # BSD nc
-          cat "nodata" | stdbuf -o0 "$3" -l "$http_nc" -vvv > "temp.log" 2>> "stderr_nc.log" &
+              cat "nodata" | $mybuffer $opt_buf $mynetcat -l "$http_nc" -vvv > "temp.log" 2>> "stderr_nc.log" &
         else # traditional nc
-          cat "nodata" | stdbuf -o0 "$3" -l -p "$http_nc" -vvv > "temp.log" 2>> "stderr_nc.log" &
+              cat "nodata" | $mybuffer $opt_buf $mynetcat -l -p "$http_nc" -vvv > "temp.log" 2>> "stderr_nc.log" &
         fi
       pid_nc=$!
       if check_listening "$http_nc"
         then
-          printf "%-35s\t%s\n" "test $1" "$2" | "$3" 127.0.0.1 "$http1" -vv 1>&2 2>> "stderr_nc.log" &
+          printf "%-35s\t%s\n" "test $1" "$2" | $mynetcat 127.0.0.1 "$http1" -vv 1>&2 2>> "stderr_nc.log" &
           pid_nce=$!
           if [ "$2" = "shouldn't work" ]
             then
@@ -364,20 +311,15 @@ connecting_ncat() {
           result=1
         fi
     else # ncat
-      if [ -n "$(command -v stdbuf)" ]
-        then
-          cat "nodata" | stdbuf -o0 "$3" -l -p "$http_nc" -vvv > "temp.log" & # 2>> "stderr_nc.log" &
-        else
-          cat "nodata" | "$3" -l -p "$http_nc" -vvv > "temp.log" & # 2>> "stderr_nc.log" &
-        fi
+      cat "nodata" | $mybuffer $opt_buf $mynetcat -l -p $http_nc -vvv > temp.log 2>> stderr_nc.log &
       pid_nc=$!
       if check_listening "$http_nc"
         then
           if ncat --version 2>&1 | grep -q -e 'Version [0-5]\.' -e 'Version [6]\.[0-1]' -e 'Version [6]\.[2][0-4]'
             then # ncat version < 6.25
-              printf "%-35s\t%s\n" "test $1" "$2" | "$3" 127.0.0.1 "$http1" -vv  1>&2 2>> "stderr_nc.log" &
+              printf "%-35s\t%s\n" "test $1" "$2" | "$mynetcat" 127.0.0.1 "$http1" -vv  1>&2 2>> "stderr_nc.log" &
             else # ncat version >= 6.25
-              printf "%-35s\t%s\n" "test $1" "$2" | "$3" 127.0.0.1 "$http1" -vv  1>&2 2>> "stderr_nc.log"
+              printf "%-35s\t%s\n" "test $1" "$2" | "$mynetcat" 127.0.0.1 "$http1" -vv  1>&2 2>> "stderr_nc.log"
             fi
           pid_nce=$!
           if [ "$2" = "shouldn't work" ]
@@ -400,16 +342,10 @@ connecting_ncat() {
 sending_ncat() {
   # starting netcat for execute tests
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   mkfifo "nodata" 2>> "stderr_nc.log"
-  if [ -n "$(command -v stdbuf)" ]
-    then
-      cat "nodata" | stdbuf -o0 "$2" 127.0.0.1 "$http1" -vv >"temp.log" 2>> "stderr_nc.log" &
-    else
-      cat "nodata" | "$2" 127.0.0.1 "$http1" -vv >"temp.log" 2>> "stderr_nc.log" &
-    fi
-  pid_nce=$!
+  cat "nodata" | $mybuffer $opt_buf $mynetcat 127.0.0.1 "$http1" -vv >"temp.log" 2>> "stderr_nc.log" &
+  pid_nce=$(pgrep -P $!)
   waiting_for "temp" "test $1"
   kill -TERM ${pid_nce} 2>> "stderr_nc.log"
   echo "somedata" > "nodata" 2>> "stderr_nc.log"
@@ -420,17 +356,16 @@ sending_ncat() {
 expected_success() {
   # expects to send the message using stunnel
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   local result=0
   if [ "$1" != "040_reload" ]
     then
-      check_ports "$1" "$2"
+      check_ports "$1"
       start_stunnel "$1"
     fi
   if no_file "error.log"
     then
-      if connecting_ncat "$1" "success" "$2"
+      if connecting_ncat "$1" "success"
         then
           finding_text "yes" "test $1.*success" "temp.log" "UNUSED PATTERN"
           result=$?
@@ -454,14 +389,13 @@ expected_success() {
 
 expected_failure() {
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   local result=0
-  check_ports "$1" "$2"
+  check_ports "$1"
   start_stunnel "$1"
   if no_file "error.log"
     then
-      if connecting_ncat "$1" "shouldn't work" "$2"
+      if connecting_ncat "$1" "shouldn't work"
         then
           if ! finding_text "no" "test $1.*shouldn't work" "temp.log" "UNUSED PATTERN"
             then # ops...stunnel works
@@ -490,14 +424,13 @@ expected_failure() {
 
 execute_program() {
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   local result=0
-  check_ports "$1" "$2"
+  check_ports "$1"
   start_stunnel "$1"
   if no_file "error.log"
     then
-      sending_ncat "$1" "$2"
+      sending_ncat "$1"
       if ! killing_stunnel
         then
           result=1
@@ -525,10 +458,9 @@ execute_program() {
 
 execute_connect() {
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   local result=0
-  check_ports "$1" "$2"
+  check_ports "$1"
   start_stunnel "$1"
   if [ "$1" = "042_inetd" ]
     then # inetd test
@@ -566,7 +498,6 @@ execute_connect() {
 
 loop_prio() {
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   local result=0
   local i=1
@@ -577,7 +508,7 @@ loop_prio() {
     else
       local serv="server_1\] accepted connection"
   fi
-  check_ports "$1" "$2"
+  check_ports "$1"
   start_stunnel "$1"
   if no_file "error.log"
     then
@@ -586,7 +517,7 @@ loop_prio() {
       kill -USR1 $(tail "stunnel.pid") 2>> "stderr_nc.log"
       while [ $i -le $max ] && [ $result -eq 0 ]
         do
-          if connecting_ncat "$1" "success" "$2"
+          if connecting_ncat "$1" "success"
             then
               finding_text "yes" "test $1.*success" "temp.log" "UNUSED PATTERN"
               result=$?
@@ -631,7 +562,6 @@ loop_prio() {
 
 loop_rr() {
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
 
   local result=0
   local i=1
@@ -639,7 +569,7 @@ loop_rr() {
   local first=0
   local second=0
   local third=0
-  check_ports "$1" "$2"
+  check_ports "$1"
   start_stunnel "$1"
   if no_file "error.log"
     then
@@ -648,7 +578,7 @@ loop_rr() {
       kill -USR1 $(tail "stunnel.pid") 2>> "stderr_nc.log"
       while [ $i -le $max ] && [ $result -eq 0 ]
         do
-          if connecting_ncat "$1" "success" "$2"
+          if connecting_ncat "$1" "success"
             then
               finding_text "yes" "test $1.*success" "temp.log" "UNUSED PATTERN"
               result=$?
@@ -704,13 +634,12 @@ loop_rr() {
 
 loop_session() {
   # $1 = test name
-  # $2 = netcat name: "ncat" / "nc"
-  # $3 = number of connections
+  # $2 = number of connections
 
   local result=0
   local i=0
-  local max=$((2*$3))
-  check_ports "$1" "$2"
+  local max=$((2*$2))
+  check_ports "$1"
   start_stunnel "$1"
   if no_file "error.log"
     then
@@ -742,20 +671,44 @@ loop_session() {
   return $result
 }
 
+myglobal() {
+  # $1 = mynetcat name: "ncat" / "nc"
+  # $2 = mynetstat name: "netstat" / "ss" / "lsof"
+  # $3 = mybuffer name: "stdbuf" / "unbuffer" / ""
+
+  mynetcat="$1"
+  mynetstat="$2"
+  mybuffer="$3"
+
+  case "$mynetstat" in
+    "netstat") opt_net="-a -n";;
+    "ss" ) opt_net="-a -n -l";;
+    "lsof" ) opt_net="-i -n -P";;
+  esac
+
+  case "$mybuffer" in
+    "stdbuf") opt_buf="-o0";;
+  esac
+  return 0
+}
+
 test_log_for() {
   # $1 = test name
   # $2 = function name
-  # $3 = netcat name: "ncat" / "nc"
-  # $4 = number of connections for loop_session
+  # $3 = number of connections for loop_session
+  # $4 = mynetcat name: "ncat" / "nc"
+  # $5 = mynetstat name: "netstat" / "ss" / "lsof"
+  # $6 = mybuffer name: "stdbuf" / "unbuffer" / ""
 
+  myglobal "$4" "$5" "$6"
   case "$2" in
-    "success") expected_success "$1" "$3";;
-    "failure") expected_failure "$1" "$3";;
-    "execute") execute_program "$1" "$3";;
-    "exe_con") execute_connect "$1" "$3";;
-    "prio") loop_prio "$1" "$3";;
-    "rr") loop_rr "$1" "$3";;
-    "session") loop_session "$1" "$3" "$4";;
+    "success") expected_success "$1";;
+    "failure") expected_failure "$1";;
+    "execute") execute_program "$1";;
+    "exe_con") execute_connect "$1";;
+    "prio") loop_prio "$1";;
+    "rr") loop_rr "$1";;
+    "session") loop_session "$1" "$3";;
   esac
   result=$?
   clean_logs
